### ISSUE TITLE
Test failure: brave.cassandra.ITTracing.usesExistingTraceId

### ISSUE THREAD

**Issue by shakuzen** [openzipkin/brave-cassandra#11]
When the build was updated so failsafe executed integration tests (see #10), a failure was revealed in `brave.cassandra.ITTracing.usesExistingTraceId`. I could reproduce this failure locally, so it seems like a genuine issue.

```
java.lang.AssertionError: 

Expecting:
 <[CLIENT]>
to contain only once:
 <[SERVER, CLIENT]>
but some elements were not found:
 <[SERVER]>

	at brave.cassandra.ITTracing.usesExistingTraceId(ITTracing.java:98)
```

**Comment by codefromthecrypt** [comment]
i believe this is because propagation is now disabled by default in
TracingSession. might be wrong
