### ISSUE TITLE
Move repository to https://github.com/apache/incubator-zipkin-brave-cassandra

### ISSUE THREAD

**Issue by michaelsembwever** [openzipkin/brave-cassandra#15]
As part of the move to the Apache Software Foundation this repository will transfer ownership to `apache` and name to `incubator-zipkin-brave-cassandra`.

See https://issues.apache.org/jira/browse/INFRA-16989

**Comment by codefromthecrypt** [comment]
repository was moved. here's a change to all the various artifacts. We need to setup jenkins to actually run this https://github.com/apache/incubator-zipkin-brave-cassandra/pull/17
