### ISSUE TITLE
Setting zipkin format to V2

### ISSUE THREAD

**Issue by jake-codes** [openzipkin/brave-cassandra#25]
It would be really helpful to be able to set the Zipkin format as an environment variable / JVM Option. 

It'd be particularly helpful for those of us who use 3rd party zipkin collectors so we don't have to manage the infrastructure of our tracing. The collector endpoints aren't completely the same as Zipkin so the package wouldn't be able to look at the collector URL and determine ahead of time which version of ZIpkin to send.

In this case, I believe the package is sending V1 whereas I'll need it to send V2 to work and I'm not sure how to switch it.

**Comment by codefromthecrypt** [comment]
hmm that's odd. will take a look

**Comment by jake-codes** [comment]
Thanks. I found it. On line 64 of Tracing.java you can set the version. In my case, I forced it to V2 but you could use the `System.getProperty()` approach for this as well.

**Comment by codefromthecrypt** [comment]
v2 support is already in, just switch the endpoint to v2 url. I'll update the README though to remove v1
