### ISSUE TITLE
Java 8 Support

### ISSUE THREAD

**Issue by jake-codes** [openzipkin/brave-cassandra#26]
Is it possible to have Java 8 supported for this project along with Java 11?

Lots of businesses are still using Java 8 because the official support for Cassandra came out just last year, I believe. Anyway, if their choice is between upgrading their Java (and doing all the regression testing, etc, to make sure there are no negative effects) or simply not using this project, many will likely choose to not use this, unfortunately.

**Comment by codefromthecrypt** [comment]
JDK (build) version is different than runtime version. We ship jars not source. Have you noticed a bytecode problem?

**Comment by codefromthecrypt** [comment]
for example, unless there's a bug in our config, this should match cassandra at Java 1.7

https://github.com/openzipkin/brave-cassandra/blob/master/pom.xml#L35-L37

**Comment by jake-codes** [comment]
Got it. Thanks a lot.

**Comment by codefromthecrypt** [comment]
no problem!
